This is the code for gradient descent.

In [ ]:
import numpy as np

In [ ]:
data = np.loadtxt("/content/drive/MyDrive/Colab Notebooks/multivariable regression/data.csv", delimiter=",")
data.shape

(100, 2)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
def step_gradient(points, learning_rate, m , c):
    m_slope = 0
    c_slope = 0
    M = len(points)
    for i in range(M):
        x = points[i, 0]
        y = points[i, 1]
        m_slope += (-2/M)* (y - m * x - c)*x
        c_slope += (-2/M)* (y - m * x - c)
        m = m - learning_rate*m_slope
        c = c - learning_rate*c_slope
    
    return m,c

In [ ]:
def gd(points, learning_rate, num_iterations):
    m = 0
    c = 0
    for i in range(num_iterations):
        m, c = step_gradient(points, learning_rate, m , c)
        print(i, " Cost: ", cost(points, m, c))
    return m, c

In [ ]:
def cost(points, m, c):
    total_cost = 0
    M = len(points)
    for i in range(M):
        x = points[i, 0]
        y = points[i, 1]
        total_cost += (1/M)*((y - m*x - c)**2)
    return total_cost



In [ ]:
def run():
    data = np.loadtxt("/content/drive/MyDrive/Colab Notebooks/multivariable regression/data.csv", delimiter=",")
    learning_rate = 0.0001
    num_iterations = 100
    m, c = gd(data, learning_rate, num_iterations)
    print(m, c)

In [ ]:
run()

0  Cost:  3172.686983446094
1  Cost:  1865.1800097253106
2  Cost:  1142.4578335423018
3  Cost:  737.2646312782974
4  Cost:  506.1350194192897
5  Cost:  371.5886655980521
6  Cost:  291.44807192166957
7  Cost:  242.5168610255285
8  Cost:  211.87123897182536
9  Cost:  192.19475178595684
10  Cost:  179.26559916076639
11  Cost:  170.59367137225277
12  Cost:  164.67437611084424
13  Cost:  160.575290766663
14  Cost:  157.70379426790814
15  Cost:  155.67409250012835
16  Cost:  154.22952313714788
17  Cost:  153.19608838815012
18  Cost:  152.4539617670214
19  Cost:  151.9195662018718
20  Cost:  151.5340200609378
21  Cost:  151.25551707353074
22  Cost:  151.05419884394476
23  Cost:  150.9086454046086
24  Cost:  150.8034394982155
25  Cost:  150.72745719764086
26  Cost:  150.67265784308088
27  Cost:  150.63322175119464
28  Cost:  150.60493266488947
29  Cost:  150.58473382265896
30  Cost:  150.5704079488361
31  Cost:  150.5603461001111
32  Cost:  150.5533804444896
33  Cost:  150.5486631569137
34  Co

In [ ]:
#now lets run the same for the other datasets where one column is linarly dependent on the other

In [ ]:
arr=np.zeros((2,20))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [ ]:
arr=arr.transpose()

In [ ]:
arr

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
for i in range(len(arr)):
  arr[i,0]=i+1
  arr[i,1]=2.5*arr[i,0]+5


In [ ]:
arr

array([[ 1. ,  7.5],
       [ 2. , 10. ],
       [ 3. , 12.5],
       [ 4. , 15. ],
       [ 5. , 17.5],
       [ 6. , 20. ],
       [ 7. , 22.5],
       [ 8. , 25. ],
       [ 9. , 27.5],
       [10. , 30. ],
       [11. , 32.5],
       [12. , 35. ],
       [13. , 37.5],
       [14. , 40. ],
       [15. , 42.5],
       [16. , 45. ],
       [17. , 47.5],
       [18. , 50. ],
       [19. , 52.5],
       [20. , 55. ]])

In [ ]:
def run2():
  data=arr
  learning_rate = 0.003
  num_iterations = 1000
  m,c=gd(data,learning_rate,num_iterations)
  print(m,c)

In [ ]:
run2()

0  Cost:  311.1934573586028
1  Cost:  143.02072088077082
2  Cost:  27.521637553874037
3  Cost:  24.403371909134176
4  Cost:  4.460633126235127
5  Cost:  8.309343691852638
6  Cost:  3.659405398479907
7  Cost:  5.202870784992207
8  Cost:  3.8129852136425018
9  Cost:  4.209910438245242
10  Cost:  3.6816491518608445
11  Cost:  3.6931650326858754
12  Cost:  3.4238144413417744
13  Cost:  3.323119702858911
14  Cost:  3.141067069129162
15  Cost:  3.014945729703688
16  Cost:  2.8682906739766407
17  Cost:  2.742849002374396
18  Cost:  2.615092590460567
19  Cost:  2.4975906742659486
20  Cost:  2.3829880648932287
21  Cost:  2.274958641608982
22  Cost:  2.1710999442370085
23  Cost:  2.0723841576935844
24  Cost:  1.977934938524011
25  Cost:  1.887912838584735
26  Cost:  1.801920192716415
27  Cost:  1.7198818597428138
28  Cost:  1.6415579087194767
29  Cost:  1.5668122831107172
30  Cost:  1.4954637609090704
31  Cost:  1.4273677528191375
32  Cost:  1.362370571232018
33  Cost:  1.3003341924481981
34  Co